# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/pixel_clocks/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/pixel_clocks/common


PRODUCT_PACKAGES += \
    SystemUIClocks-BigNum \
    SystemUIClocks-Calligraphy \
    SystemUIClocks-Flex \
    SystemUIClocks-Growth \
    SystemUIClocks-Inflate \
    SystemUIClocks-Metro \
    SystemUIClocks-NumOverlap
